# Generated by Django 5.0.1 on 2024-02-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_id_alter_listing_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('Maison', 'House'), ('Villa', 'Condo'), ('Appartement', 'Townhouse')], default='Maison', max_length=50),
        ),
    ]
