# Generated by Django 5.0.2 on 2024-02-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_home_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('En Vente', 'For Sale'), ('A Louer', 'For Rent')], default='En Vente', max_length=50),
        ),
    ]
